blank_issues_enabled: true
contact_links:
  - name: New ObjFW ticket
    url: https://objfw.nil.im/tktnew
    about:
      Please use this to create a new ticket. You can also report issues on
      GitHub, but this is preferred.
  - name: Existing ObjFW tickets
    url: https://objfw.nil.im/reportlist
    about: Please use this to look for existing tickets.
  - name: ObjFW Forum
    url: https://objfw.nil.im/forum
    about: Please use this if you have questions or want support.
  - name: ObjFW Matrix Room
    url: https://matrix.to/#/%23objfw:nil.im
    about: Please use this for interactive questions and support.
  - name: ObjFW IRC Channel
    url: https://webchat.freenode.net/?channels=objfw
    about:
      Please use this for interactive questions and support - it is bridged to 
      the Matrix room above.
